name: hack_js
description: Vulnerability scans on dependencies for JavaScript projects

inputs:
  node_version:
    description: 'Node.js version to use'
    required: true

  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run vulnerability scan
      id: audit
      run: npm audit --audit-level=moderate || echo "audit_failed=true" >> $GITHUB_ENV
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Enforce dependency check
      if: env.audit_failed == 'true'
      run: exit 1
      shell: bash
